#!/usr/bin/env python3
import os
import time
import sys
import threading

backup_base_path = r'/var/backups'
bin_path = r'/usr/local/bin/epd'
config_path = r'/etc/gateway'
need_reboot = False

os.chdir(os.path.dirname(os.path.abspath(__file__)))
timestamp = str(time.time())
app_name = os.path.basename(bin_path)

def backup():
    '''备份'''
    cur_backup_path = os.path.join(backup_base_path, timestamp)
    os.system("mkdir -p %s" % cur_backup_path)
    if config_path:         # 备份原始配置文件
        os.system("mkdir %s" % os.path.join(cur_backup_path, 'config'))
        os.system("cp %s/* %s -rf" % (config_path, os.path.join(cur_backup_path, 'config')))
    if bin_path:            # 备份应用文件
        os.system("cp %s %s -rf" % (bin_path, cur_backup_path))

def rollback():
    '''回滚'''
    backup_path = os.path.join(backup_base_path, timestamp)
    os.chdir(backup_path)
    os.system("cp %s/* /etc/gateway -rf" % os.path.join(backup_path, 'config'))
    os.system("cp %s %s -rf" % (app_name, os.path.dirname(bin_path)))

count = 10
def reboot():
    global count
    count = count - 1
    print("\r reboot after %d ......" % count)
    if count:
        th = threading.Timer(1, reboot)
        th.start()
    else:
        print("reboot now ......")
        os.system("reboot")

# 安装开始
try:
    print("install start ......")
    backup()
    print("backup complete")
    os.chdir(os.path.dirname(os.path.abspath(__file__)))     # 切换至当前目录
    print("kill %s process" % app_name)
    os.system("/home/root/kill_process %s" % app_name)      # 杀死所有应用
    os.system("cp %s %s -rf" % (app_name, os.path.dirname(bin_path)))   # 拷贝应用程序
    os.system("cp config/* /etc/gateway -rf")
    print("\r reboot after 10 seconds")
    if need_reboot:
        reboot()
except:
    rollback()
    sys.exit(1)
